Alpha Proposal
solidity-labs-io/forge-proposal-simulator pull request #46
Opened 2024-03-17 23:30 UTC by ElliotFriedman

Create proposal structure as defined in issue [45](https://github.com/solidity-labs-io/forge-proposal-simulator/issues/45).

TODO:

- [x] update docs

2024-03-18 11:48 UTC, anajuliabit requested changes
I loved this, LFG! Just minor things:

2024-03-18 11:48 UTC, anajuliabit commented on examples/timelock/TIMELOCK_01.sol
> +        return TimelockProposal.getCalldata();
what is the point of overriding here?

2024-03-18 11:48 UTC, anajuliabit commented on proposals/AlphaProposal.sol
> +abstract contract AlphaProposal is Proposal {
wouldn't it be better to implement this directly in the Proposal class for a cleaner solution?

2024-03-18 11:48 UTC, anajuliabit commented on proposals/AlphaProposal.sol
> +        for (uint i = 0; i < data.length; i++) {
```suggestion
        for (uint256 i = 0; i < data.length; i++) {
```

2024-03-18 11:48 UTC, anajuliabit commented on proposals/AlphaProposal.sol
> +            buffer[i * 2] = characters[uint(uint8(data[i] >> 4))];
```suggestion
            buffer[i * 2] = characters[uint256(uint8(data[i] >> 4))];
```

2024-03-18 11:48 UTC, anajuliabit commented on proposals/AlphaProposal.sol
> +            buffer[i * 2 + 1] = characters[uint(uint8(data[i] & 0x0f))];
```suggestion
            buffer[i * 2 + 1] = characters[uint256(uint8(data[i] & 0x0f))];
```

2024-03-18 11:48 UTC, anajuliabit commented on proposals/TimelockProposal.sol
> +    function getCalldata() public view virtual override returns (bytes memory) {
natspec

2024-03-18 11:48 UTC, anajuliabit commented on proposals/TimelockProposal.sol
> +        revert("do not call getcalldata on timelock proposal");
why can't it be called?

2024-03-18 14:56 UTC, prateek105 commented on examples/multisig/MULTISIG_01.sol
> +contract MULTISIG_01 is AlphaProposal, MultisigProposal {
`buildModifier` not used for this proposal. If we are keeping this as a simple proposal then we can avoid inheriting `AlphaProposal` contract here.

2024-03-18 22:23 UTC, anajuliabit commented on examples/timelock/TIMELOCK_01.sol
> +        return TimelockProposal.getCalldata();
would it be better to implement AlphaProposal in the Proposal so we don't need to have 2 parent classes?

2024-03-18 23:12 UTC, anajuliabit requested changes

2024-03-18 23:12 UTC, anajuliabit commented on examples/governor-bravo/BRAVO_02.sol
> +import {Proposal} from "@proposals/Proposal.sol";
remove

2024-03-18 23:12 UTC, anajuliabit commented on examples/governor-bravo/BRAVO_03.sol
> +import {Proposal} from "@proposals/Proposal.sol";
remove

2024-03-18 23:12 UTC, anajuliabit commented on examples/governor-bravo/BRAVO_04.sol
> +/// using the AlphaProposal type.
```suggestion
/// using the GovernorBravoProposal type.
```

2024-03-18 23:12 UTC, anajuliabit commented on examples/multisig/MULTISIG_02.sol
> +import {Proposal} from "@proposals/Proposal.sol";
remove

2024-03-18 23:12 UTC, anajuliabit commented on examples/multisig/MULTISIG_03.sol
> +import {Proposal} from "@proposals/Proposal.sol";
remove

2024-03-18 23:53 UTC, anajuliabit approved these changes
LGTM

2024-03-19 15:12 UTC, prateek105 commented on proposals/AlphaProposal.sol
> +    modifier buildModifier(address caller, Addresses addresses) {
yes right, we can call the `_outerBuild` in `run`

2024-03-19 15:14 UTC, prateek105 approved these changes
lgtm.

2024-03-19 15:55 UTC, merged