Print ERC20 token transfers and ETH transfers in proposals
solidity-labs-io/forge-proposal-simulator pull request #83
Opened 2024-07-26 17:15 UTC by prateek105

2024-08-01 19:26 UTC, anajuliabit requested changes

2024-08-01 19:26 UTC, anajuliabit commented on src/proposals/Proposal.sol
> +            );
could you please add some inline comments here? it's hard to understand what is going on

2024-08-01 19:26 UTC, anajuliabit commented on src/proposals/Proposal.sol
> +            }
please add some inline comments explain this logic

2024-08-01 19:26 UTC, anajuliabit commented on src/proposals/Proposal.sol
> +        bool isEthTransfer;
instead of adding an extra field `isEthTransfer` you could set `tokenAddress` to  `address(0)` and then call vm.label(address(0), "ETH")

2024-08-01 19:26 UTC, anajuliabit commented on src/proposals/Proposal.sol
> +        if (selector == 0xa9059cbb) {
to improve readability you could import ERC20 interface and then call `ERC20.transfer.selector`

2024-08-01 19:26 UTC, anajuliabit commented on src/proposals/Proposal.sol
> +        else if (selector == 0x23b872dd) {
to improve readability you could import ERC20 interface and then call ERC20.transferFrom.selector

2024-08-01 19:26 UTC, anajuliabit commented on src/proposals/Proposal.sol
> +    mapping(address addr => bool isAffected) private _isProposalAffectedAddress;
this doesn't need to be a storage variable, it could be placed in memory inside the _processStateDiffChanges function

2024-08-05 11:26 UTC, prateek105 commented on src/proposals/Proposal.sol
> +            );
done.

2024-08-05 11:26 UTC, prateek105 commented on src/proposals/Proposal.sol
> +            }
done.

2024-08-05 11:30 UTC, prateek105 commented on src/proposals/Proposal.sol
> +        bool isEthTransfer;
Removed `isEthTransfer` but have not labelled `address(0)` as "ETH" because in case there are transactions to address zero we will get a wrong label.

2024-08-05 11:33 UTC, prateek105 commented on src/proposals/Proposal.sol
> +        if (selector == 0xa9059cbb) {
We are not using OZ submodule and to do this we will either need to install OZ submodule or copy the OZ interface here. I think the inline comment makes this code readable and we can avoid importing erc20 interface altogether. What do u think?

2024-08-05 11:39 UTC, prateek105 commented on src/proposals/Proposal.sol
> +    mapping(address addr => bool isAffected) private _isProposalAffectedAddress;
Although this mapping is used in a single method but we cannot pass this mapping down to 3 internal function calls. Also the script gas consumption doesn't affect the broadcasted transactions gas cost.

2024-08-06 20:51 UTC, anajuliabit submitted a review, later dismissed
LGTM

2024-08-13 05:55 UTC, ElliotFriedman approved these changes
LGTM!

2024-08-13 18:23 UTC, merged