update `addresses.json` file using `vm.writeJson`
solidity-labs-io/forge-proposal-simulator pull request #84
Opened 2024-08-01 14:33 UTC by prateek105

https://github.com/solidity-labs-io/forge-proposal-simulator/issues/78

2024-08-13 05:37 UTC, ElliotFriedman commented on addresses/Addresses.sol
> +
what is the purpose of adding this?

2024-08-13 05:48 UTC, ElliotFriedman commented on addresses/Addresses.sol
> +
ok, what you're saying is if you added this address, and then change it in the same proposal, this handles that case

2024-08-13 05:48 UTC, ElliotFriedman commented on test/Addresses.t.sol
> +            "Address: 0x9679E26bf0C470521DE83Ad77BB1bf1e7312f739 already set on chain: 31337"
would be great to see a unit test that adds an address, then writes it to JSON, then reads that JSON back in to see that the file was correctly written to

2024-08-13 14:54 UTC, prat-gpt commented on test/Addresses.t.sol
> +            "Address: 0x9679E26bf0C470521DE83Ad77BB1bf1e7312f739 already set on chain: 31337"
added test here [35b8930](https://github.com/solidity-labs-io/forge-proposal-simulator/pull/84/commits/35b89303279cc21da8b394891e917a3ba93e07cb)

2024-08-13 18:24 UTC, ElliotFriedman commented on test/Addresses.t.sol
> +        addresses.isAddressSet("TEST");
also add a getAddress to these tests

2024-08-13 18:26 UTC, ElliotFriedman requested changes
Would be great to see some docs here so that users can understand the new environment variables

2024-08-15 04:01 UTC, ElliotFriedman commented on docs/overview/architecture/proposal-functions.md
> +    -   **DO_UPDATE_ADDRESS_JSON**: When set to true, updates the `Addresses.json` file with the newly added and changed addresses.
Add default values to the docs

2024-08-15 04:01 UTC, ElliotFriedman commented on docs/overview/architecture/proposal-functions.md
> +    -   **DO_AFTER_DEPLOY_MOCK**: When set to true, initiates post-deployment mocking processes. Essential for testing or simulating scenarios after deployment.
```suggestion
    -   **DO_AFTER_DEPLOY_MOCK**: When set to true, initiates post-deployment mocking processes. Used to simulate an action that has not happened yet for testing such as dealing tokens for testing or simulating scenarios after deployment.
```

2024-08-15 04:02 UTC, ElliotFriedman commented on src/proposals/Proposal.sol
> +    /// @notice flag to update the `Addresses.json` file with the newly added and changed addresses
add default values to natspec

2024-08-15 04:04 UTC, ElliotFriedman commented on test/Addresses.t.sol
> +        addresses.addAddress("TEST", test, 123, true);
let's do a more involved test than a single address being added

Mix it up a bit, here are some ideas:
- add two addresses
- add one address, then change where it points
- mix in writing to the file, then creating a new addresses object reading from that file, check isAddressSet and getAddress using both the chain id and without the chain id as parameters.

2024-08-15 20:13 UTC, ElliotFriedman commented on docs/overview/architecture/proposal-functions.md
> +    -   **DO_DEPLOY**: When set to true, triggers the deployment of contracts on-chain. Default value is false.
```suggestion
    -   **DO_DEPLOY**: When set to true, triggers the deployment of contracts on-chain. Default value is true.
```

2024-08-15 20:14 UTC, ElliotFriedman approved these changes
LGTM!

2024-08-15 20:58 UTC, merged

2024-08-15 23:16 UTC, anajuliabit reviewed
this is so cool, LGTM!